-- Initial schema. Portable across PostgreSQL and H2 (MODE=PostgreSQL).

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    plan          VARCHAR(32)  NOT NULL DEFAULT 'free',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE leads (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(320) NOT NULL UNIQUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    converted_at TIMESTAMP
);

-- Speeds up the subscribers view, which filters unconverted leads.
CREATE INDEX idx_leads_converted_at ON leads (converted_at);
