-- Books and claims for the Readrop giveaway platform.

ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(120);

CREATE TABLE books (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    author      VARCHAR(255) NOT NULL,
    genre       VARCHAR(80)  NOT NULL,
    condition   VARCHAR(10)  NOT NULL DEFAULT 'GOOD',
    description VARCHAR(600),
    city        VARCHAR(120) NOT NULL,
    owner_id    BIGINT       NOT NULL REFERENCES users(id),
    status      VARCHAR(16)  NOT NULL DEFAULT 'AVAILABLE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_books_status ON books (status);
CREATE INDEX idx_books_owner  ON books (owner_id);

CREATE TABLE book_claims (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT       NOT NULL REFERENCES books(id),
    claimer_id  BIGINT       NOT NULL REFERENCES users(id),
    message     VARCHAR(400),
    status      VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_claims_book    ON book_claims (book_id);
CREATE INDEX idx_claims_claimer ON book_claims (claimer_id);
